//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thuctapchuyenmon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTNhapThuCung
    {
        public string MaPN { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<double> GiaNhap { get; set; }
        public string MaThuCung { get; set; }
        public string MaLoai { get; set; }
        public string TenThuCung { get; set; }
        public string Donvi { get; set; }
    
        public virtual PhieuNhap PhieuNhap { get; set; }
        public virtual LoaiThuCung LoaiThuCung { get; set; }
    }
}
