//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thuctapchuyenmon
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHUKIEN
    {
        public string Maphukien { get; set; }
        public string Tenphukien { get; set; }
        public string MaHD { get; set; }
        public int soluong { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual PHUKIEN PHUKIEN { get; set; }
    }
}
