//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaitaplonAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calamviec
    {
        public string MaNV { get; set; }
        public System.DateTime NgayLV { get; set; }
        public Nullable<System.TimeSpan> ThoiGianBD { get; set; }
        public Nullable<System.TimeSpan> ThoiGianKT { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
