//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaitaplonAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiThuCung
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LoaiThuCung()
        {
            this.CTNhapThuCungs = new HashSet<CTNhapThuCung>();
        }
    
        public string MaLoai { get; set; }
        public string TenLoai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTNhapThuCung> CTNhapThuCungs { get; set; }
        public virtual LoaiThuCung LoaiThuCung1 { get; set; }
        public virtual LoaiThuCung LoaiThuCung2 { get; set; }
    }
}
