//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaitaplonAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuongTungThang
    {
        public string MaNV { get; set; }
        public int Thang { get; set; }
        public Nullable<double> Luong { get; set; }
        public Nullable<double> ThuongPhat { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
