//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaitaplonAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuongPhat
    {
        public string MaThuongphat { get; set; }
        public string MaNV { get; set; }
        public Nullable<System.DateTime> Ngay { get; set; }
        public string Loai { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string Lydo { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
